#' @title Genetic Correlation Estimation
#' @description The Horizontal and Vertical Pleiotropy (HVP) model applied to individual-level data. This method disentangles horizontal from vertical pleiotropy effects, providing unbiased genetic correlation estimates specifically attributed to horizontal pleiotropy. It corrects the genetic correlation derived from bivariate REML.
#' @param varg Genetic variance of the outcome variable estimated in a univariate context.
#' @param varb Genetic variance of the exposure variable estimated in a univariate context.
#' @param covg_hat Genetic covariance between the exposure variable ('varb') and the outcome variable ('varg'), as estimated by the conventional bivariate GREML method using genome-wide SNPs.
#' @param v_varg Variance of 'varg' from the information matrix generated by the conventional bivariate GREML method, or the square of the standard error of 'varg'.
#' @param v_varb Variance of 'varb' from the information matrix generated by the conventional bivariate GREML method, or the square of the standard error of 'varb'.
#' @param v_covg_hat Variance of 'covg_hat' from the information matrix generated by the conventional bivariate GREML method, or the square of the standard error of 'covg_hat'.
#' @param cov_varg_varb Covariance between 'varb' and 'varg', derived from the information matrix.
#' @param cov_varg_covg_hat Covariance between 'varg' and the genetic covariance ('covg_hat') between 'varb' and 'varg', derived from the information matrix.
#' @param cov_varb_covg_hat Covariance between 'varb' and the genetic covariance ('covg_hat') between 'varb' and 'varg', derived from the information matrix.
#' @param tau The causal effect of the exposure on the outcome, as estimated by a robust Mendelian Randomization (MR) method.
#' @importFrom stats D pchisq
#' @return A matrix containing:
#' \item{Estimate}{Corrected estimates of 'Heritability', 'Genetic Covariance', and 'Genetic Correlation'.}
#' \item{Standard Error}{Standard errors of the corrected estimates.}
#' \item{P_value}{P-values from chi-square tests for the corrected estimates.}
#' @export

hvp = function (varg,varb,covg_hat,v_varg,v_varb,v_covg_hat,cov_varg_varb,cov_varg_covg_hat,cov_varb_covg_hat,tau) {


  f1=expression( varg - tau^2*varb-2*tau*(covg_hat-tau*varb ))


  av1=array(0,3)

  av1[1]=eval(D(f1,'varg'))
  av1[2]=eval(D(f1,'varb'))
  av1[3]=eval(D(f1,'covg_hat'))


  ov1=matrix(0,3,3)

  ov1[1,1]=v_varg
  ov1[1,2]=cov_varg_varb
  ov1[1,3]=cov_varg_covg_hat
  ov1[2,1]=ov1[1,2]
  ov1[2,2]=v_varb
  ov1[2,3]=cov_varb_covg_hat
  ov1[3,1]=ov1[1,3]
  ov1[3,2]=ov1[2,3]
  ov1[3,3]=v_covg_hat

  #variance of the vara
  aoa1=sqrt(t(av1)%*%ov1%*%(av1))
  z1=list(h2=eval(f1),h2SE=as.numeric(aoa1), p_value=as.numeric(pchisq((eval(f1)/aoa1)^2,1,lower.tail=F)))


  f2=expression(covg_hat - tau * varb )

  av2=array(0,2)
  av2[1]=eval(D(f2,'varb'))
  av2[2]=eval(D(f2,'covg_hat'))

  ov2=matrix(0,2,2)
  ov2[1,1]=v_varb
  ov2[2,2]=v_covg_hat
  ov2[2,1]=cov_varb_covg_hat
  ov2[1,2]=cov_varb_covg_hat

  #variance of the covg
  aoa2=sqrt(t(av2)%*%ov2%*%(av2))
  z2 = list(covg=eval(f2),covgSE=as.numeric(aoa2), p_value=as.numeric(pchisq((eval(f2)/aoa2)^2,1,lower.tail=F)))

  f3=expression((covg_hat-tau*varb)/sqrt((varg-tau^2*varb-2*tau*(covg_hat-tau*varb))*varb))


  av3=array(0,3)

  av3[1]=eval(D(f3,'varg'))
  av3[2]=eval(D(f3,'varb'))
  av3[3]=eval(D(f3,'covg_hat'))


  ov3=matrix(0,3,3)

  ov3[1,1]=v_varg
  ov3[1,2]=cov_varg_varb
  ov3[1,3]=cov_varg_covg_hat
  ov3[2,1]=ov3[1,2]
  ov3[2,2]=v_varb
  ov3[2,3]=cov_varb_covg_hat
  ov3[3,1]=ov3[1,3]
  ov3[3,2]=ov3[2,3]
  ov3[3,3]=v_covg_hat

  #variance of corrected rG
  aoa3=sqrt(t(av3)%*%ov3%*%(av3))
  z3=list(rG=eval(f3),rGSE=as.numeric(aoa3), p_value=as.numeric(pchisq((eval(f3)/aoa3)^2,1,lower.tail=F)))
  #combine the corrected estimates
  cat(sprintf("%-32s: Estimate = %.4f, SE = %.4f, P-value = %s\n",
              "h2 outcome (corrected)", z1$h2,
              z1$h2SE,
              format.pval(z1$p_value)))
  cat(sprintf("%-32s: Estimate = %.4f, SE = %.4f, P-value = %s\n",
              "Genetic Covariance (corrected)", z2$covg,
              z2$covgSE,
              format.pval(z2$p_value)))
  cat(sprintf("%-32s: Estimate = %.4f, SE = %.4f, P-value = %s\n",
              "Genetic Correlation (corrected)", z3$rG,
              z3$rGSE,
              format.pval(z3$p_value)))

  return(invisible())
}
